/**
 * copy-crown — mirror the isomorphic Crown Card canvas modules into the
 * functions build tree so the Cloud Function can render the SAME 1.91:1 card as
 * the client WITHOUT duplicating the implementation (handoff §3 line 138 —
 * "중복 구현 금지"). Functions use a separate tsconfig (`rootDir: src`) and cannot
 * import the repo-root `lib/` directly, so we copy `lib/crown/{formats,canvas/*}`
 * into `functions/src/_crown/` at build time. The copies are git-ignored and
 * regenerated by `npm run build` (predeploy) — the single source of truth stays
 * `lib/crown/*`.
 */
import { mkdirSync, copyFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); // functions/scripts
const root = join(here, "..", "..");                  // repo root
const libCrown = join(root, "lib", "crown");
const dest = join(here, "..", "src", "_crown");
const destCanvas = join(dest, "canvas");

mkdirSync(destCanvas, { recursive: true });

// Pure render contract + the canvas modules drawLink/drawQR depend on.
copyFileSync(join(libCrown, "formats.ts"), join(dest, "formats.ts"));
for (const file of readdirSync(join(libCrown, "canvas"))) {
  if (file.endsWith(".ts")) {
    copyFileSync(join(libCrown, "canvas", file), join(destCanvas, file));
  }
}

console.log("[copy-crown] mirrored lib/crown/{formats,canvas/*} → functions/src/_crown");
