/**
 * copy-ranking — mirror the pure C-3 ranking logic into the functions build
 * tree so `scheduleRankingCache` runs the SAME computeRankings / anomalyRules
 * as the client without duplicating them (handoff §3 "중복 구현 금지", same
 * pattern as copy-crown). Functions use a separate tsconfig (`rootDir: src`)
 * and cannot import the repo-root `lib/`, so we copy the import-free pure
 * modules into `functions/src/_ranking/` at build time. The copies are
 * git-ignored and regenerated by `npm run build` — single source: `lib/ranking`.
 */
import { mkdirSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url)); // functions/scripts
const root = join(here, "..", "..");                  // repo root
const libRanking = join(root, "lib", "ranking");
const dest = join(here, "..", "src", "_ranking");

mkdirSync(dest, { recursive: true });

// Import-free pure modules the cron needs. rateFormatter is UI-only (skipped).
for (const file of ["rankingTypes.ts", "computeRankings.ts", "anomalyRules.ts"]) {
  copyFileSync(join(libRanking, file), join(dest, file));
}

console.log("[copy-ranking] mirrored lib/ranking/{rankingTypes,computeRankings,anomalyRules} → functions/src/_ranking");
